/**
 * PR Linker
 * Links Canvas CLI sessions to GitHub pull requests.
 * Adds session metadata as PR comments for traceability.
 *
 * Usage: canvas pr link <number>
 */

import { spawn } from 'child_process';

export interface PRLink {
  prNumber: number;
  sessionId: string;
  linkedAt: string;
  repository?: string;
}

/**
 * Link a session to a PR by adding a comment
 */
export async function linkSessionToPR(prNumber: number, sessionId: string): Promise<boolean> {
  const body = [
    '### Canvas CLI Session Linked',
    '',
    `Session: \`${sessionId}\``,
    `Linked at: ${new Date().toISOString()}`,
    '',
    '_This comment was automatically generated by Canvas CLI._',
  ].join('\n');

  try {
    await execGh(['pr', 'comment', String(prNumber), '--body', body]);
    return true;
  } catch {
    return false;
  }
}

/**
 * Get PR details
 */
export async function getPRDetails(prNumber: number): Promise<any | null> {
  try {
    const output = await execGh(['pr', 'view', String(prNumber), '--json',
      'number,title,state,author,body,headRefName,baseRefName,additions,deletions,files']);
    return JSON.parse(output);
  } catch {
    return null;
  }
}

/**
 * Create a PR from the current branch
 */
export async function createPR(options: {
  title: string;
  body: string;
  base?: string;
  draft?: boolean;
}): Promise<string | null> {
  const args = ['pr', 'create', '--title', options.title, '--body', options.body];
  if (options.base) args.push('--base', options.base);
  if (options.draft) args.push('--draft');

  try {
    return await execGh(args);
  } catch {
    return null;
  }
}

/**
 * Execute a gh CLI command
 */
function execGh(args: string[]): Promise<string> {
  return new Promise((resolve, reject) => {
    const proc = spawn('gh', args, {
      timeout: 30000,
      env: { ...process.env },
    });

    let stdout = '';
    let stderr = '';

    proc.stdout?.on('data', (data) => { stdout += data.toString(); });
    proc.stderr?.on('data', (data) => { stderr += data.toString(); });

    proc.on('exit', (code) => {
      if (code === 0) resolve(stdout.trim());
      else reject(new Error(stderr || `gh exited with code ${code}`));
    });
    proc.on('error', reject);
  });
}
