/**
 * Canvas CLI Pro — feature gating for the Pro tier ($15/month)
 *
 * Reads Pro subscription status from the local user config (~/.canvas-cli/config.json)
 * and gates Pro-only features. Free features are always available.
 */

import { createRequire } from 'module';
import chalk from 'chalk';
import { loadConfig, saveConfig } from '../config.js';

const _require = createRequire(import.meta.url);
const crypto = _require('crypto');

/**
 * Features available only to Pro subscribers.
 */
export const PRO_FEATURES = [
  'persistent_memory',
  'multi_project_context',
  'nerve_core_integration',
  'team_sharing',
  'custom_agents',
  'advanced_analytics',
] as const;

/**
 * Features available to all users (free tier).
 */
export const FREE_FEATURES = [
  'basic_chat',
  'file_ops',
  'shell_exec',
  'semantic_search',
] as const;

export type ProFeature = (typeof PRO_FEATURES)[number];
export type FreeFeature = (typeof FREE_FEATURES)[number];
export type Feature = ProFeature | FreeFeature;

/**
 * The monthly price of the Pro plan, in USD.
 */
export const PRO_PRICE_USD = 15;

/**
 * Check whether the current user has an active Pro subscription.
 *
 * A user is considered Pro when `pro_status` is 'active' in the local config.
 * Offline license keys are also honored via {@link validateLicenseKeyOffline}.
 *
 * @returns true if the user has an active Pro subscription or valid license key
 */
export function isProUser(): boolean {
  const config = loadConfig();

  // Active subscription via Stripe
  if (config.pro_status === 'active') {
    return true;
  }

  // Offline license key still valid
  if (config.pro_license_key) {
    return validateLicenseKeyOffline(config.pro_license_key);
  }

  return false;
}

/**
 * Check whether a feature is available to the current user.
 *
 * Free features are always available. Pro features require an active Pro
 * subscription (see {@link isProUser}).
 *
 * @param feature - the feature key to check
 * @returns true if the feature is available
 */
export function checkFeature(feature: Feature): boolean {
  if ((FREE_FEATURES as readonly string[]).includes(feature)) {
    return true;
  }

  if ((PRO_FEATURES as readonly string[]).includes(feature)) {
    return isProUser();
  }

  // Unknown feature — default to free (available)
  return true;
}

/**
 * Render an upgrade prompt to the console when a free user attempts to use a
 * Pro-only feature.
 *
 * @param feature - the Pro feature the user tried to access
 * @returns the formatted upgrade message (also printed to stdout)
 */
export function promptUpgrade(feature: Feature): string {
  const featureLabel = prettifyFeature(feature);

  const lines = [
    '',
    chalk.magenta.bold('┌──────────────────────────────────────────────┐'),
    chalk.magenta.bold('│') + chalk.white.bold('  ⚡ Canvas Pro required') + chalk.magenta.bold('                       │'),
    chalk.magenta.bold('└──────────────────────────────────────────────┘'),
    '',
    chalk.gray(`  ${featureLabel} is a Pro feature.`),
    chalk.gray(`  Upgrade for $${PRO_PRICE_USD}/month to unlock:`),
    '',
    ...PRO_FEATURES.map(f => chalk.gray(`    • ${prettifyFeature(f)}`)),
    '',
    chalk.cyan('  Upgrade now:'),
    chalk.cyan('    canvas pro subscribe'),
    '',
    chalk.gray('  Or activate an existing license key:'),
    chalk.gray('    canvas pro activate <key>'),
    '',
  ];

  const message = lines.join('\n');
  console.log(message);
  return message;
}

/**
 * Get the current Pro status for display (e.g. in the UI badge).
 */
export function getProStatus(): {
  isPro: boolean;
  status: string;
  email?: string;
  hasLicenseKey: boolean;
} {
  const config = loadConfig();
  const isPro = isProUser();
  return {
    isPro,
    status: config.pro_status || 'free',
    email: config.pro_email,
    hasLicenseKey: !!config.pro_license_key,
  };
}

/**
 * Mark the user as Pro (active subscription) and persist to config.
 */
export function setProActive(email?: string, licenseKey?: string): void {
  const config = loadConfig();
  saveConfig({
    ...config,
    pro_status: 'active',
    pro_email: email ?? config.pro_email,
    pro_license_key: licenseKey ?? config.pro_license_key,
  });
}

/**
 * Clear Pro status (cancelled / inactive).
 */
export function setProInactive(): void {
  const config = loadConfig();
  saveConfig({
    ...config,
    pro_status: 'inactive',
  });
}

/**
 * Offline validation of a license key without contacting Stripe.
 *
 * License keys are generated by {@link generateLicenseKey} in billing.ts and
 * embed a checksum so they can be validated locally.
 */
export function validateLicenseKeyOffline(key: string): boolean {
  if (!key || typeof key !== 'string') return false;

  // Format: CVPRO-<userIdHash>-<checksum>
  const parts = key.split('-');
  if (parts.length !== 3 || parts[0] !== 'CVPRO') return false;

  const [, payload, checksum] = parts;
  if (!payload || !checksum) return false;

  const expected = crypto
    .createHash('sha256')
    .update(payload + ':canvas-pro')
    .digest('hex')
    .substring(0, 8);

  return checksum === expected;
}

/**
 * Convert a snake_case feature key into a human-readable label.
 */
function prettifyFeature(feature: string): string {
  return feature
    .split('_')
    .map(w => w.charAt(0).toUpperCase() + w.slice(1))
    .join(' ');
}